
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: avatar_app_development
  password: argentina


test:
  <<: *default
  database: avatar_app_test
  password: argentina

production:
  <<: *default
  database: avatar_app_production
  username: avatar_app
  password: <%= ENV["AVATAR_APP_DATABASE_PASSWORD"] %>
